package view;

import DAO.DAOAluno;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.DAOCurso;
import java.text.DecimalFormat;
import java.util.List;
import model.Curso;

/**
 * Tela de cadastro de cursos do sistema escolar.
 * <p>
 * Permite inserir novos cursos, listar os cursos cadastrados
 * e limpar os campos do formulário.
 * </p>
 * 
 * @author Paulo
 * @version 1.0
 */
public class CadastroDeCursos extends javax.swing.JFrame {

    private DefaultTableModel modelo;

    /**
    * Construtor da tela de cadastro de cursos.
    */
    public CadastroDeCursos() {
        initComponents();
        
        // Configura o modelo da tabela com colunas específicas
        modelo = new DefaultTableModel(
                new Object[]{"ID do Curso", "Curso", "Carga Horária"}, 0
        );

        tabelaCursos.setModel(modelo);
        // Lista os cursos já cadastrados no banco
        listarCursos();
        
        // Centraliza a janela
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNomeCurso = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        lbCargaHoraria = new javax.swing.JLabel();
        txtCargaHoraria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCursos = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cursos");

        lbNomeCurso.setText("Nome do Curso: ");

        lbCargaHoraria.setText("Carga Horária: ");

        tabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID do Curso", "Curso", "Carga Horária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCursos.setEnabled(false);
        tabelaCursos.setMinimumSize(new java.awt.Dimension(60, 80));
        jScrollPane1.setViewportView(tabelaCursos);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNomeCurso)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(txtNomeCurso)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCargaHoraria)
                                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar)))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCurso)
                    .addComponent(lbCargaHoraria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnSalvar))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInicial menu = new TelaInicial();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvarCurso();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeCursos().setVisible(true);
            }
        });
    }

    /**
     * Lê os dados digitados pelo usuário, valida e salva um curso no banco.
     */
    private void salvarCurso() {

        Curso curso = new Curso();

        // Lê os dados dos campos de texto
        String nomeCurso = txtNomeCurso.getText().trim();
        String cargaHoraria = txtCargaHoraria.getText().trim();

        // Validação do Curso
        if (validarCurso(txtNomeCurso.getText().trim()) == false) {
            JOptionPane.showMessageDialog(null,
                    "Nome do Curso não pode ser vazio!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Validação da Carga Horária
        if (validarCargaHoraria(txtCargaHoraria.getText().trim()) == false) {
            JOptionPane.showMessageDialog(null,
                    "Digite um valor válido!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Preenche o objeto curso
        curso.setNomeCurso(nomeCurso);
        curso.setCargaHoraria(Integer.parseInt(cargaHoraria));

        // Salva no banco via DAO
        DAOCurso dao = new DAOCurso();
        dao.salvar(curso);

        // Mensagem de sucesso e atualização da tabela
        JOptionPane.showMessageDialog(this, "Curso salvo com sucesso!");
        listarCursos();
        limparCampos();
    }


    /**
     * Lista todos os cursos na tabela da interface.
     */
    private void listarCursos() {
        tabelaCursos.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de atualizar

        DAOCurso dao = new DAOCurso();
        List<Curso> lista = dao.listar();

        // Adiciona cada curso como uma nova linha
        for (Curso c : lista) {
            modelo.addRow(new Object[]{
                c.getId_curso(),
                c.getNomeCurso(),
                c.getCargaHoraria()
            });
        }
    }

    /**
     * Limpa os campos do formulário e coloca o cursor no campo Nome do Curso.
     */
    private void limparCampos() {
        txtNomeCurso.setText("");
        txtCargaHoraria.setText("");
        txtNomeCurso.requestFocus();
    }

    /**
     * Validação do que será digitado no campo txtCurso
     * @param curso String recebida através do painel, futuramente
     * @return Retorna o curso contendo somente letras, acentos e espaços
     */
    public static boolean validarCurso(String curso){
        if (curso == null || curso.isBlank()) {
            return false;
        }
        
        //Aceita letras, acentos, espaços e mais alguns símbolos
        return curso.matches("[A-Za-zÀ-Ÿà-ÿ ]+");
    }
    
    /**
     * Valida a carga horária, só aceita números
     * @param cargaHoraria Será recebida do painel futuramente
     * @return retorna o true caso o valor seja ideal
     */
    public static boolean validarCargaHoraria(String cargaHoraria){
        if (cargaHoraria == null || cargaHoraria.isBlank()) {
            return false;
        }
        
        //Aceita somente números, recusa vazios
        return cargaHoraria.matches("\\d+");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCargaHoraria;
    private javax.swing.JLabel lbNomeCurso;
    private javax.swing.JTable tabelaCursos;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtNomeCurso;
    // End of variables declaration//GEN-END:variables
}
