package view;

import DAO.DAOAluno;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import util.DataUtils;

/**
 * Tela de cadastro de alunos do sistema escolar.
 * <p>
 * Permite inserir novos alunos, listar os alunos cadastrados e limpar os campos
 * do formulário.
 * </p>
 *
 * @author Paulo
 * @version 1.0
 */
public class CadastroDeAlunos extends javax.swing.JFrame {

    private DefaultTableModel modelo;

    /**
     * Construtor da tela de cadastro.
     * <p>
     * Inicializa os componentes, configura a tabela de alunos e centraliza a
     * tela na tela do usuário.
     * </p>
     */
    public CadastroDeAlunos() {
        initComponents();

        // Configura o modelo da tabela com colunas específicas
        modelo = new DefaultTableModel(
                new Object[]{"ID", "Nome", "E-mail", "Telefone"}, 0
        );
        tabelaAluno.setModel(modelo);

        // Lista os alunos já cadastrados no banco
        listarAlunos();

        // Centraliza a janela
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();
        txtTelefone = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        lbNascimento = new javax.swing.JLabel();
        txtDataBR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Alunos");

        jLabel1.setText("E-mail:");

        lbNome.setText("Nome do Aluno:");

        lbTelefone.setText("Telefone:");

        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Aluno", "E-mail", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAluno);

        txtTelefone.setColumns(30);

        txtNome.setColumns(30);

        txtEmail.setColumns(30);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        lbNascimento.setText("Nascimento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalvar))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNome)
                        .addGap(189, 189, 189)
                        .addComponent(lbTelefone))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDataBR))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNascimento)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(lbTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnSalvar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInicial menu = new TelaInicial();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvarAluno();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeAlunos().setVisible(true);
            }
        });
    }

    /**
     * Lê os dados digitados pelo usuário, valida e salva um aluno no banco.
     */
    private void salvarAluno() {

        // Cria um objeto Aluno para guardar os dados digitados
        Aluno aluno = new Aluno();

        // Lê os dados dos campos de texto
        String nome = txtNome.getText().trim();
        String email = txtEmail.getText().trim();
        String telefone = txtTelefone.getText().trim();
        String dataBR = txtDataBR.getText().trim();

        // Valida o nome
        if (validarNome(txtNome.getText()) == false) {
            JOptionPane.showMessageDialog(null, "Nome inválido",
                    "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Valida o email
        if (validarEmail(txtEmail.getText()) == false) {
            JOptionPane.showMessageDialog(null, "E-mail inválido!",
                    "Erro", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Validação da Data
        if (DataUtils.validarData(dataBR) == null) {
            return;
        }
        //Converte a data digitada
        String dataSQL = DataUtils.converterDataParaMySQL(dataBR);

        // Preenche o objeto aluno
        aluno.setNome(nome);
        aluno.setEmail(email);
        aluno.setTelefone(telefone);
        aluno.setDataNasc(dataSQL);

        // Envia para o banco de dados via DAO
        DAOAluno dao = new DAOAluno();
        dao.salvar(aluno);

        // Mensagem de sucesso e atualização da tabela
        JOptionPane.showMessageDialog(this, "Aluno salvo com sucesso!");
        listarAlunos();
        limparCampos();
    }

    /**
     * Lista todos os alunos ativos na tabela da interface.
     */
    protected void listarAlunos() {
        tabelaAluno.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de atualizar

        DAOAluno dao = new DAOAluno();
        List<Aluno> lista = dao.listar();

        // Adiciona cada aluno como uma nova linha
        for (Aluno a : lista) {
            modelo.addRow(new Object[]{
                a.getId_aluno(),
                a.getNome(),
                a.getEmail(),
                a.getTelefone()
            });
        }
    }

    /**
     * Limpa os campos do formulário e coloca o cursor no campo Nome.
     */
    private void limparCampos() {
        txtNome.setText("");
        txtEmail.setText("");
        txtTelefone.setText("");
        txtDataBR.setText("");
        txtNome.requestFocus();
    }

//    /**
//     * Converte a data digitada pelo usuário (dataBR) para uma data aceita pelo
//     * SQL
//     *
//     * @param dataBR será convertido em dataSQL
//     */
//    public String converterDataParaMySQL(String dataBR) {
//        try {
//            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
//            SimpleDateFormat formatoSaida = new SimpleDateFormat("yyyy-MM-dd");
//
//            // Converte a string de entrada para o formato MySQL
//            Date data = formatoEntrada.parse(dataBR);
//            return formatoSaida.format(data);
//
//        } catch (Exception e) {
//            System.out.println(" Erro ao converter data: " + e.getMessage());
//            return null;
//        }
//    }
    /**
     * Método usado para validação do email
     *
     * @param email email digitado no campo txtEmail do painel
     * @return o resultado da validação REGEX - true se for válido, false se não
     */
    public static boolean validarEmail(String email) {
        if (email == null || email.isEmpty()) {
            return false;
        }

        // Valida estrutura básica de e-mail
        String regex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";

        return email.matches(regex);
    }

    /**
     * Método usado para validar o nome de uma pessoa
     *
     * @param nome nome digitado pelo usuário no campo txtNome do painel
     * @return resultado da validação REGEX - true se válido, false se não
     */
    public static boolean validarNome(String nome) {
        if (nome == null || nome.isEmpty()) {
            return false;
        }

        // Aceita letras, acentos e espaços entre os nomes
        String regex = "^[A-Za-zÀ-Ÿà-ÿ]+( [A-Za-zÀ-Ÿà-ÿ]+)*$";

        return nome.matches(regex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbNascimento;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTextField txtDataBR;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
