package view;

import DAO.DAOAluno;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.DAOCurso;
import java.text.DecimalFormat;
import java.util.List;
import model.Curso;

/**
 * Tela de cadastro de cursos do sistema escolar.
 * <p>
 * Permite inserir novos cursos, listar os cursos cadastrados
 * e limpar os campos do formulário.
 * </p>
 * 
 * @author Paulo
 * @version 1.0
 */
public class CadastroDeCursos extends javax.swing.JFrame {

    private DefaultTableModel modelo;

    /**
    * Construtor da tela de cadastro de cursos.
    */
    public CadastroDeCursos() {
        initComponents();
        
        // Configura o modelo da tabela com colunas específicas
        modelo = new DefaultTableModel(
                new Object[]{"ID do Curso", "Curso", "Carga Horária"}, 0
        );

        tabelaCursos.setModel(modelo);
        // Lista os cursos já cadastrados no banco
        listarCursos();
        
        // Centraliza a janela
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTItulo = new javax.swing.JLabel();
        lbNomeCurso = new javax.swing.JLabel();
        txtNomeCurso = new javax.swing.JTextField();
        lbCargaHoraria = new javax.swing.JLabel();
        txtCargaHoraria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCursos = new javax.swing.JTable();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTItulo.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbTItulo.setText("Cadastro de Cursos");

        lbNomeCurso.setText("Nome do Curso: ");

        lbCargaHoraria.setText("Carga Horária: ");

        tabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID do Curso", "Curso", "Carga Horária"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaCursos.setEnabled(false);
        jScrollPane1.setViewportView(tabelaCursos);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbCargaHoraria)
                                    .addComponent(lbNomeCurso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSair)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSalvar))
                                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lbTItulo)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lbTItulo)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeCurso)
                    .addComponent(txtNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCargaHoraria))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInicial menu = new TelaInicial();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvarCurso();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroDeCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroDeCursos().setVisible(true);
            }
        });
    }

    /**
     * Lê os dados digitados pelo usuário, valida e salva um curso no banco.
     */
    private void salvarCurso() {

        Curso curso = new Curso();

        // Lê os dados dos campos de texto
        String nomeCurso = txtNomeCurso.getText().trim();
        String cargaHoraria = txtCargaHoraria.getText().trim();

        // Valida campos obrigatórios
        if (nomeCurso.isEmpty() || cargaHoraria.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Os campos Nome do Curso e Carga Horária são obrigatórios!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Preenche o objeto curso
        curso.setNomeCurso(nomeCurso);
        curso.setCargaHoraria(Integer.parseInt(cargaHoraria));

        // Salva no banco via DAO
        DAOCurso dao = new DAOCurso();
        dao.salvar(curso);

        // Mensagem de sucesso e atualização da tabela
        JOptionPane.showMessageDialog(this, "Curso salvo com sucesso!");
        listarCursos();
        limparCampos();
    }


    /**
     * Lista todos os cursos na tabela da interface.
     */
    private void listarCursos() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaCursos.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de atualizar

        DAOCurso dao = new DAOCurso();
        List<Curso> lista = dao.listar();

        // Adiciona cada curso como uma nova linha
        for (Curso c : lista) {
            modelo.addRow(new Object[]{
                c.getId_curso(),
                c.getNomeCurso(),
                c.getCargaHoraria()
            });
        }
    }

    /**
     * Limpa os campos do formulário e coloca o cursor no campo Nome do Curso.
     */
    private void limparCampos() {
        txtNomeCurso.setText("");
        txtCargaHoraria.setText("");
        txtNomeCurso.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCargaHoraria;
    private javax.swing.JLabel lbNomeCurso;
    private javax.swing.JLabel lbTItulo;
    private javax.swing.JTable tabelaCursos;
    private javax.swing.JTextField txtCargaHoraria;
    private javax.swing.JTextField txtNomeCurso;
    // End of variables declaration//GEN-END:variables
}
