/*
 * Classe responsável por exibir a interface de exclusão de matrículas.
 * Permite listar todos os alunos e cursos, selecionar um pelo ID e desvinculá-los.
 */
package view;

import model.Aluno;
import DAO.DAOAluno;
import DAO.DAOCurso;
import DAO.DAOMatricula;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Curso;
import model.Matricula;

/**
 * Tela para excluir ou desativar a matrícula de um aluno em um curso.
 *
 * @author Paulo
 */
public class ExcluirMatricula extends javax.swing.JFrame {

    private DefaultTableModel modelo;

    /**
     * Construtor da tela. Inicializa os componentes gráficos, configura a
     * tabela de alunos e preenche os dados.
     */
    public ExcluirMatricula() {
        initComponents();

        modelo = new DefaultTableModel(
                new Object[]{"ID", "Nome", "Curso"}, 0
        );

        tabelaAluno.setModel(modelo);
        listarMatriculasAtivas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMatricula = new javax.swing.JLabel();
        txtIdMatricula = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();
        lbMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Excluir Matrícula");
        setPreferredSize(new java.awt.Dimension(420, 450));

        lbMatricula.setText("Matrícula:");

        txtIdMatricula.setColumns(35);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaAluno);

        lbMensagem.setText("Essa ação desvinculará o aluno do curso.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMensagem)
                    .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addGap(213, 213, 213)
                        .addComponent(btnExcluir))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbMatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnExcluir))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            // Captura o texto do campo e converte para inteiro
            int id_desejado = Integer.parseInt(txtIdMatricula.getText());

            // Chama o método que faz a exclusão
            excluirMatricula(id_desejado);

        } catch (NumberFormatException e) {
            // Caso o campo esteja vazio ou com texto inválido
            JOptionPane.showMessageDialog(this,
                    "Por favor, insira um ID válido (número inteiro).",
                    "Erro de entrada",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInicial menu = new TelaInicial();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirMatricula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirMatricula().setVisible(true);
            }
        });
    }

    /**
     * Método que remove ou desativa a matrícula do curso para o aluno
     * informado.
     *
     * @param id_desejado ID do curso que será desvinculado
     */
    private void excluirMatricula(int id_desejado) {
        DAOMatricula dao = new DAOMatricula();
        List<Matricula> lista = dao.listar();

        boolean encontrado = false;

        for (Matricula m : lista) {
            if (m.getId_matricula()== id_desejado) {
                // Confirmação antes de excluir
                int resposta = JOptionPane.showConfirmDialog(
                        this,
                        "Deseja realmente desativar a matrícula?",
                        "Confirmação",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE
                );

                if (resposta == JOptionPane.YES_OPTION) {
                    dao.excluir(m); // Marca como inativa
                    JOptionPane.showMessageDialog(this, "Matrícula marcada como inativa com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Ação cancelada.");
                }
                encontrado = true;
                break;
            }
        }

        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Matrícula não encontrada.",
                    "Erro", JOptionPane.WARNING_MESSAGE);
        }
        listarMatriculasAtivas();
    }

    /**
     * Lista todos os alunos cadastrados na tabela. Este método atualiza a
     * tabela removendo os dados antigos e inserindo os alunos atuais do banco.
     */
    protected void listarMatriculasAtivas() {
        // Limpa a tabela antes de preencher
        modelo.setRowCount(0);

        DAOMatricula dao = new DAOMatricula();
        List<Matricula> lista = dao.listar(); // Lista todas as matrículas

        for (Matricula m : lista) {
            modelo.addRow(new Object[]{
                m.getId_matricula(),
                m.getNomeAluno(),
                m.getNomeCurso()
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbMensagem;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTextField txtIdMatricula;
    // End of variables declaration//GEN-END:variables
}
