/*
 * Classe responsável por exibir a interface de exclusão de cursos.
 * Permite listar todos os cursos, selecionar um pelo ID e marcá-lo como inativo.
 */
package view;

import model.Aluno;
import DAO.DAOAluno;
import DAO.DAOCurso;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Curso;

/**
 * Tela para excluir ou marcar cursos como inativos.
 * @author Paulo
 */
public class ExcluirCurso extends javax.swing.JFrame {

    private DefaultTableModel modelo;


    /**
     * Construtor da classe.
     * Inicializa os componentes visuais e configura a tabela para exibir os cursos.
     */
    public ExcluirCurso() {
        initComponents();

        modelo = new DefaultTableModel(
                new Object[]{"ID", "Nome"}, 0
        );

        tabelaAluno.setModel(modelo);
        listarAlunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbExcluirCurso = new javax.swing.JLabel();
        lbIdCurso = new javax.swing.JLabel();
        txtIdCurso = new javax.swing.JTextField();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAluno = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbExcluirCurso.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbExcluirCurso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbExcluirCurso.setText("Excluir Curso");

        lbIdCurso.setText("ID do Aluno:");

        txtIdCurso.setColumns(35);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome"
            }
        ));
        jScrollPane1.setViewportView(tabelaAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluir))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbIdCurso)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbExcluirCurso)
                                    .addComponent(txtIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbExcluirCurso)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdCurso)
                    .addComponent(txtIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            // Captura o texto do campo e converte para inteiro
            int id_desejado = Integer.parseInt(txtIdCurso.getText());

            // Chama o método que faz a exclusão
            excluirCurso(id_desejado);

        } catch (NumberFormatException e) {
            // Caso o campo esteja vazio ou com texto inválido
            JOptionPane.showMessageDialog(this,
                    "Por favor, insira um ID válido (número inteiro).",
                    "Erro de entrada",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInicial menu = new TelaInicial();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirCurso().setVisible(true);
            }
        });
    }

    /**
     * Marca o curso como inativo, dado o ID informado.
     * @param id_desejado id informado para a exclusão
     */
    private void excluirCurso(int id_desejado) {
        DAOCurso dao = new DAOCurso();
        List<Curso> lista = dao.listar();

        boolean encontrado = false;

        for (Curso c : lista) {
            if (c.getId_curso() == id_desejado) {
                // Confirmação do usuário antes de excluir
                int resposta = JOptionPane.showConfirmDialog(
                        this,
                        "Deseja realmente marcar este curso como inativo?",
                        "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE
                );

                if (resposta == JOptionPane.YES_OPTION) {
                    dao.excluir(c);
                    JOptionPane.showMessageDialog(this, "Curso marcado como inativo com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Ação cancelada.");
                }
                encontrado = true;
                break;
            }
        }

        // Se não encontrar o curso pelo ID
        if (!encontrado) {
            JOptionPane.showMessageDialog(this, "Curso não encontrado.",
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * Lista todos os cursos na tabela.
     */
    protected void listarAlunos() {
        DefaultTableModel modelo = (DefaultTableModel) tabelaAluno.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de atualizar

        DAOAluno dao = new DAOAluno();
        List<Aluno> lista = dao.listar();

        for (Aluno a : lista) {
            modelo.addRow(new Object[]{
                a.getId_aluno(),
                a.getNome()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbExcluirCurso;
    private javax.swing.JLabel lbIdCurso;
    private javax.swing.JTable tabelaAluno;
    private javax.swing.JTextField txtIdCurso;
    // End of variables declaration//GEN-END:variables
}
