package view;

import DAO.DAOAluno;
import DAO.DAOCurso;
import DAO.DAOMatricula;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Curso;
import model.Matricula;
import java.sql.SQLException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import util.DataUtils;

/**
 * Tela de matrícula de alunos em cursos.
 * <p>
 * Permite selecionar um aluno, um curso e a data da matrícula,
 * salvar no banco e listar as matrículas já existentes.
 * </p>
 * 
 * @author Paulo
 * @version 1.0
 */
public class MatriculasEmCursos extends javax.swing.JFrame {

    private DefaultTableModel modelo;

    /**
     * Construtor da tela.
     */
    public MatriculasEmCursos() {
        initComponents();

        // Configura a tabela
        modelo = new DefaultTableModel(
                new Object[]{"ID","Aluno", "Curso", "Data da Matrícula"}, 0
        );

        tabelaMatricula.setModel(modelo);
        setLocationRelativeTo(null);
        
        // Carrega dados iniciais
        listarMatriculas();
        carregarAlunos();
        carregarCursos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAluno = new javax.swing.JLabel();
        comboAluno = new javax.swing.JComboBox<>();
        lbCruso = new javax.swing.JLabel();
        comboCurso = new javax.swing.JComboBox<>();
        lbCruso1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMatricula = new javax.swing.JTable();
        btnSair = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtDataBR = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Matricular Aluno");

        lbAluno.setText("Aluno: ");

        lbCruso.setText("Curso: ");

        comboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCursoActionPerformed(evt);
            }
        });

        lbCruso1.setText("Data da Matrícula: ");

        tabelaMatricula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Aluno", "Curso", "Data da Matrícula"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaMatricula);

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbAluno)
                            .addComponent(lbCruso)
                            .addComponent(comboAluno, 0, 357, Short.MAX_VALUE)
                            .addComponent(comboCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataBR, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCruso1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSalvar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAluno)
                    .addComponent(lbCruso1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataBR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbCruso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSair)
                    .addComponent(btnSalvar))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCursoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        salvarMatricula();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TelaInicial menu = new TelaInicial();
        menu.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatriculasEmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatriculasEmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatriculasEmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatriculasEmCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MatriculasEmCursos().setVisible(true);
            }
        });
    }

    /**
     * Salva uma matrícula no banco.
     * Valida data e evita matrícula futura.
     */
    private void salvarMatricula() {
        Aluno aluno = (Aluno) comboAluno.getSelectedItem();
        Curso curso = (Curso) comboCurso.getSelectedItem();
        String dataBR = txtDataBR.getText().trim();

        //Verificações simples
        if (aluno == null || curso == null) {
            JOptionPane.showMessageDialog(this,
                    "Selecione um aluno e um curso válidos!",
                    "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Validação da Data
        if (DataUtils.validarData(dataBR) == null) {
            return;
        }
        //Converte a data digitada
        String dataSQL = DataUtils.converterDataParaMySQL(dataBR);

        // Cria um novo objeto Matricula e associa Aluno, Curso e Data
        Matricula matricula = new Matricula();
        matricula.setAluno(aluno);
        matricula.setCurso(curso);
        matricula.setDataCurso(dataSQL);

        DAOMatricula dao = new DAOMatricula();
        try {
            // Salva no banco
            dao.salvar(matricula);
            JOptionPane.showMessageDialog(this, "Matrícula salva com sucesso!");
            listarMatriculas(); // Atualiza tabela
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    e.getMessage(),
                    "Erro", JOptionPane.WARNING_MESSAGE);
        }
        listarMatriculas();
        limparCampos();
    }

    private void listarMatriculas() {
        modelo.setRowCount(0); // Limpa tabela

        DAOMatricula dao = new DAOMatricula();
        List<Matricula> lista = dao.listar();

        // Adiciona os dados à tabela
        for (Matricula m : lista) {
            modelo.addRow(new Object[]{
                m.getId_matricula(),
                m.getNomeAluno(),
                m.getNomeCurso(),
                m.getDataCurso()
            });
        }
    }

    /**
     * Carrega os alunos no comboBox.
     */
    private void carregarAlunos() {
        DAOAluno dao = new DAOAluno();
        List<Aluno> alunos = dao.listar();

        comboAluno.removeAllItems();
        for (Aluno a : alunos) {
            comboAluno.addItem(a);
        }
    }

    /**
     * Carrega os cursos no comboBox.
     */
    private void carregarCursos() {
        DAOCurso dao = new DAOCurso();
        List<Curso> cursos = dao.listar();

        comboCurso.removeAllItems();
        for (Curso c : cursos) {
            comboCurso.addItem(c);
        }
    }
    
        /**
     * Converte a data digitada pelo usuário (dataBR) para uma data aceita pelo
     * SQL
     *
     * @param dataBR será convertido em dataSQL
     */
    public String converterDataParaMySQL(String dataBR) {
        try {
            SimpleDateFormat formatoEntrada = new SimpleDateFormat("dd/MM/yyyy");
            SimpleDateFormat formatoSaida = new SimpleDateFormat("yyyy-MM-dd");

            // Converte a string de entrada para o formato MySQL
            Date data = formatoEntrada.parse(dataBR);
            return formatoSaida.format(data);

        } catch (Exception e) {
            System.out.println(" Erro ao converter data: " + e.getMessage());
            return null;
        }
    }
    
        /**
     * Limpa os campos digitados pelo usuário
     */
    private void limparCampos() {
        txtDataBR.setText("");
        txtDataBR.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<Aluno> comboAluno;
    private javax.swing.JComboBox<Curso> comboCurso;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAluno;
    private javax.swing.JLabel lbCruso;
    private javax.swing.JLabel lbCruso1;
    private javax.swing.JTable tabelaMatricula;
    private javax.swing.JTextField txtDataBR;
    // End of variables declaration//GEN-END:variables
}
