package view;

import view.CadastroDeAlunos;
import view.CadastroDeCursos;
import view.MatriculasEmCursos;
import view.ExcluirAluno;

/**
 * Tela principal do sistema.
 *
 * @author Paulo
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Construtor da tela inicial. Inicializa os componentes gráficos e
     * centraliza a janela na tela.
     */
    public TelaInicial() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbMenuInicial = new javax.swing.JLabel();
        lbAluno = new javax.swing.JLabel();
        lbCurso = new javax.swing.JLabel();
        lbMatricula = new javax.swing.JLabel();
        btnNovaMatricula = new javax.swing.JButton();
        btnExcluirMatricula = new javax.swing.JButton();
        btnNovoCurso = new javax.swing.JButton();
        btnExcluirCurso = new javax.swing.JButton();
        btnNovoAluno = new javax.swing.JButton();
        btnExcluirAluno = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbMenuInicial.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbMenuInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenuInicial.setText("Menu Inicial");

        lbAluno.setText("Aluno:");

        lbCurso.setText("Curso:");

        lbMatricula.setText("Matrícula: ");

        btnNovaMatricula.setText("Novo");
        btnNovaMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaMatriculaActionPerformed(evt);
            }
        });

        btnExcluirMatricula.setText("Excluir");
        btnExcluirMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirMatriculaActionPerformed(evt);
            }
        });

        btnNovoCurso.setText("Novo");
        btnNovoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCursoActionPerformed(evt);
            }
        });

        btnExcluirCurso.setText("Excluir");
        btnExcluirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCursoActionPerformed(evt);
            }
        });

        btnNovoAluno.setText("Novo");
        btnNovoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoAlunoActionPerformed(evt);
            }
        });

        btnExcluirAluno.setText("Excluir");
        btnExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirAlunoActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMatricula)
                            .addComponent(lbCurso)
                            .addComponent(lbAluno))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnNovoAluno, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnNovoCurso))
                                    .addComponent(btnNovaMatricula))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnExcluirCurso)
                                    .addComponent(btnExcluirAluno)
                                    .addComponent(btnExcluirMatricula)))
                            .addComponent(lbMenuInicial)))
                    .addComponent(btnSair))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbMenuInicial)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbAluno)
                    .addComponent(btnNovoAluno)
                    .addComponent(btnExcluirAluno))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCurso)
                    .addComponent(btnNovoCurso)
                    .addComponent(btnExcluirCurso))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMatricula)
                    .addComponent(btnNovaMatricula)
                    .addComponent(btnExcluirMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnNovoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoAlunoActionPerformed
        // TODO add your handling code here:
        abrirCadastroAlunos();
    }//GEN-LAST:event_btnNovoAlunoActionPerformed

    private void btnNovoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCursoActionPerformed
        // TODO add your handling code here:
        abrirCadastroCursos();
    }//GEN-LAST:event_btnNovoCursoActionPerformed

    private void btnNovaMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaMatriculaActionPerformed
        // TODO add your handling code here:
        abrirCadastroMatricula();
    }//GEN-LAST:event_btnNovaMatriculaActionPerformed

    private void btnExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAlunoActionPerformed
        // TODO add your handling code here:
        abrirExcluirAlunos();
    }//GEN-LAST:event_btnExcluirAlunoActionPerformed

    private void btnExcluirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCursoActionPerformed
        // TODO add your handling code here:
        abrirExcluirCursos();
    }//GEN-LAST:event_btnExcluirCursoActionPerformed

    private void btnExcluirMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirMatriculaActionPerformed
        // TODO add your handling code here:
        abrirExcluirMatricula();
    }//GEN-LAST:event_btnExcluirMatriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }
    // Métodos Auxiliares
    /**
     * Abre a tela de cadastro de alunos.
     */
    private void abrirCadastroAlunos() {
        CadastroDeAlunos menuAluno = new CadastroDeAlunos();
        menuAluno.setLocationRelativeTo(null);
        menuAluno.setVisible(true);
    }

    /**
     * Abre a tela de exclusão de alunos.
     */
    private void abrirExcluirAlunos() {
        ExcluirAluno excluirAluno = new ExcluirAluno();
        excluirAluno.setLocationRelativeTo(null);
        excluirAluno.setVisible(true);
    }

    /**
     * Abre a tela de cadastro de cursos.
     */
    private void abrirCadastroCursos() {
        CadastroDeCursos menuCurso = new CadastroDeCursos();
        menuCurso.setLocationRelativeTo(null);
        menuCurso.setVisible(true);
    }

    /**
     * Abre a tela de exclusão de cursos.
     */
    private void abrirExcluirCursos() {
        ExcluirCurso excluirCurso = new ExcluirCurso();
        excluirCurso.setLocationRelativeTo(null);
        excluirCurso.setVisible(true);
    }

    /**
     * Abre a tela de cadastro de matrículas.
     */
    private void abrirCadastroMatricula() {
        MatriculasEmCursos menuMatricula = new MatriculasEmCursos();
        menuMatricula.setLocationRelativeTo(null);
        menuMatricula.setVisible(true);
    }

    /**
     * Abre a tela de exclusão de matrículas.
     */
    private void abrirExcluirMatricula() {
        ExcluirMatricula excluirMatricula = new ExcluirMatricula();
        excluirMatricula.setLocationRelativeTo(null);
        excluirMatricula.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirAluno;
    private javax.swing.JButton btnExcluirCurso;
    private javax.swing.JButton btnExcluirMatricula;
    private javax.swing.JButton btnNovaMatricula;
    private javax.swing.JButton btnNovoAluno;
    private javax.swing.JButton btnNovoCurso;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel lbAluno;
    private javax.swing.JLabel lbCurso;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbMenuInicial;
    // End of variables declaration//GEN-END:variables
}
